### Readme - _DataProcessing.ipynb_

#### This notebook creates a dataset for media measurement using Snowflake Tables and _.py_ modules. Some people may call it the ET part of ETL.

- Modules live in `./modules/`
- Each module contains a discrete step of the data creation process. 
- Steps are wrapped within callable functions to keep the notebook environment clean. 
- Each block in this notebook calls one of these functions which creates transient datasets in the folder where this code is run.
- Once complete, data can be loaded for modeling and analysis.

---

### Modules:
   
1. `read_snowflake_data.py` Accessess the necessary Snowflake tables and writes them to `./data/cache/` as _.parquet_ files.
2. `data_cleaner.py` Contains a master function _clean_all_data_ which calls sub-functions. These sub-functions each clean and transform a different cached _.parquet_ file and saves to `./data/clean/`
3. `merge_data.py` Combines the cleaned datasets into a single master panel which is saved to `./data/master.parquet`
4. `macro_tools.py` Pulls two macroeconomic controls - the **WEI** and **PCE** from the _FRED_ API. It also manages the cleaning, transformation and attachment of these controls to the master panel
5. `reverse_causality_controls.py` Somewhat of a work in progress, generally meant to handle reverse causality. 

---

### Known Issues:

- New media spending dataset has broken the chain, `merge_data` currently being fixed
- `macro_tools` was a vibe coded slopfest and is currently getting cleaned up.
    - `macro_tools.ipynb` is the live testing environment
    - The main script will be updated once testing is finished

- Revese Causality needs help, it's basically non-existent currently

- The GA dataset may be inaccurate, but no one around here really seems to know anymore

- The filestructure needs a lot of help

---

In [1]:
# --- Autoreload for Custom Modules ---

%load_ext autoreload
%autoreload 2

In [2]:
# --- Community Imports ---

import snowflake.snowpark as snowpark
from snowflake.snowpark.session import Session
import pandas as pd
import datetime as dt
import os
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
# --- Snowflake Credentials & Connector ---

connection_parameters = {
    "account": os.getenv("SNOWFLAKE_ACCOUNT"),
    "user": os.getenv("SNOWFLAKE_USER"),
    "authenticator": os.getenv("SNOWFLAKE_AUTHENTICATOR"),
    "insecure_mode":True
}

session = Session.builder.configs(connection_parameters).create()

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://dish.okta.com/app/snowflake/exk9ewak82R5btDoW2p7/sso/saml?SAMLRequest=pZLLbtswEEV%2FRWDXEinFrxCWAzWGUwVJa9iKW3dHS7RNiCJVDmU5%2FfpSfhTpItl0R5B3eO7MnfHdsZLegRsQWsUoDAjyuMp1IdQuRi%2FZzB8hDyxTBZNa8Ri9ckB3kzGwStY0aexeLfivhoP13EcKaPcQo8YoqhkIoIpVHKjN6TJ5fqJRQCgD4MY6HLqUFCAca29tTTFu2zZobwJtdjgihGByi52qk3xCbxD1x4zaaKtzLa8lR9fTO4gQk16HcApHmF8KPwt1HsFHlM1ZBPRLls39%2Bbdlhrzk2t29VtBU3Cy5OYicvyyezgbAOVivkoiEN6OgAb91s%2FOjoDbiwCyXQpUBKN1uJSt5rqu6sQ4RuBPe8gJLvRNucOk0RnUpCpaSbJbD4CAehiFZlcdsu%2BHJ%2BnEvfxTr3%2BG8etykBS8eBpDmyFtdY466mFOAhqeqC9e6KxINfBL6pJ9FhEZ92hsGYb%2F3E3lTZ1AoZk%2BV1w4KAftAl5adnLG6xn9NY34sb3nLylG06G%2FsVH%2BP6iEG0LgLDp13h57oZvJfExnjt19ddvKriymdzrUU%2Bas306Zi9v0UwyA83YjC356klFdMyKQoDAdwaUqp23vDnY8YWdNwhCdn6r%2FLP%2FkD&RelayState=ver%3A1-hint%3A9387093498435230-ETMsDgAAAZuP1lWSABRBRVMvQ0JDL1BLQ1M1UGFkZGluZwEAABAAEOaRWzxsRFNBRHQHYZqhBR0AAACwLPtLnLymWXWvhPuZ80e5bsu16y9Q6L2vWlf0crSQpPlQFrp6KMbFQKGhPFUofjhatUDC%2F%2F1RrTCRa6JqZGelAkdtpr7ydEySFPdIHLlVN4%2Bj3R%2FmTmTuntFLwMa8O4sbAKQG%2BrBTOtycUdiTKYPqgcG7z%2BJwA48T5Qt9vsVLyGXS3akyUVFP9ux%2BEbhfAS2AsG5jjqQIW9kf8PYPdt3ljdpJp35RJ0o2dXn6XQZL%2Bp8AFAHi5dvkr1s8ig20dqk9jzrPtbJ1 to authenticate...

## Snowflake Data Read-Ins
#### This is pretty self-explanatory

**Things to know:**

- Pulls in each dataset using the snowpark API
- Requires Snowflake credentials
- Grabs data if it's older than the specified hour age in the script
- _Writes to the uncleaned data cache_ `./data/cache/`

In [4]:
# --- Snowflake Data Read

from modules.read_snowflake_data import fetch_and_cache_data
fetch_and_cache_data(session=session)

All data caches are fresh. No queries needed.

## Data Cleaning

#### This script cleans and transforms each dataset

- Because of how markets work, we have to create a manual mapping. `market_map_os_to_bst` is effectively a giant dictionary that allows us to run the _.map_ function and join Opensignal market performance data to Boosts business-level outcomes

- Frankly, I've kind of lost track of what's going on here. I'm about 80% sure `market_map_ga_to_bst` is not getting used anymore, it was for robustness checking.
    - We're using population as a proxy for media investment by market to construct a _shift-share_. I did some correlation analysis, it works trust me.

- Writes cleaned to `./data/clean/`

In [5]:
# --- Initial Data Cleaning

from modules.data_cleaner import clean_all_data
clean_all_data()

Local Data Description

,Date,Digital,Festivals and Sponsorships,OOH,Other_Local,Radio
count,8603,8603.000000,8603.000000,8603.000000,8603.000000,8603.000000
mean,2025-02-13 13:54:24.396140800,7930.167692,3756.662252,95122.667572,3453.508895,21001.269788
min,2024-01-09 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024-09-28 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2025-03-01 00:00:00,0.000000,0.000000,52670.000000,0.000000,10013.620000
75%,2025-06-17 00:00:00,5417.280000,1007.190000,150000.000000,0.000000,30009.780000
max,2026-01-27 00:00:00,137488.510000,130011.440000,668549.470000,114521.280000,263954.560000
std,NaN,17208.845974,10253.329988,113752.046648,14465.420428,30706.865543

National Data Description

/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/data_cleaner.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Date'] = pd.to_datetime(cleaned_df['Date'])

                                Date          Spend
count                         133407  133407.000000
mean   2025-04-01 00:00:00.000000512    3247.133462
min              2024-07-01 00:00:00       0.000000
25%              2024-11-15 00:00:00       0.000000
50%              2025-04-01 00:00:00       0.000000
75%              2025-08-16 00:00:00      18.262500
max              2025-12-31 00:00:00  762752.874000
std                              NaN   23055.057508

OpenSignal Data Description

                      Date    Population  Population_Percent
count                 4200  4.200000e+03         4200.000000
mean   2024-10-16 00:00:00  1.609047e+06            0.004762
min    2024-01-01 00:00:00  9.203000e+03            0.000027
25%    2024-05-24 06:00:00  3.650290e+05            0.001080
50%    2024-10-16 12:00:00  7.758550e+05            0.002295
75%    2025-03-08 18:00:00  1.698056e+06            0.005029
max    2025-08-01 00:00:00  2.238730e+07            0.065007
std                    NaN  2.513327e+06            0.007437

GA Data Description

/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/data_cleaner.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Date'] = pd.to_datetime(df_filtered['Date'])
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/data_cleaner.py:126: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Market'] = df_filtered['Market'].map(mapping_dict).fillna(df_filtered['Market'])

                                Date             GA
count                         203348  203348.000000
mean   2025-04-21 16:18:45.385054208      19.272975
min              2024-07-01 00:00:00    -399.000000
25%              2024-12-01 00:00:00       2.000000
50%              2025-05-03 00:00:00       7.000000
75%              2025-09-15 00:00:00      20.000000
max              2025-12-28 00:00:00    1153.000000
std                              NaN      41.076610

New National Data Description

/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/data_cleaner.py:148: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Date'] = pd.to_datetime(cleaned_df['Date'])

                                Date          Spend
count                          42876   42876.000000
mean   2025-06-24 10:51:23.123425792   15676.849461
min              2025-01-01 00:00:00       0.010000
25%              2025-04-03 00:00:00     652.287500
50%              2025-06-16 00:00:00    3240.990000
75%              2025-09-16 00:00:00   14000.820000
max              2025-12-22 00:00:00  586732.980000
std                              NaN   37845.139566

All data has been cleaned and saved successfully.

# The assertation issue is due to the inclusion of sales channels ---

In [6]:
# -- Merge datasets, build master panel

from modules.merge_data import create_master_panel
create_master_panel()

/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a

Using intersecting date range (excluding opensignal lag at end): 2024-07-01 to 2025-12-22
Imputing OpenSignal from 2025-08-01 → 2025-12-01

/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a
/Users/Ben.Pharris/Documents/Code Gallery/Media Measurement/modules/merge_data.py:70: RankWarning: Polyfit may be poorly conditioned
  b, a = np.polyfit(x, y, 1)  # slope b, intercept a

❌ Assertion FAILED for: Instrument_Affiliate
Series are different

Series values are different (17.03704 %)
[index]: [2024-07-01T00:00:00.000000000, 2024-07-02T00:00:00.000000000, 2024-07-03T00:00:00.000000000, 2024-07-04T00:00:00.000000000, 2024-07-05T00:00:00.000000000, 2024-07-06T00:00:00.000000000, 2024-07-07T00:00:00.000000000, 2024-07-08T00:00:00.000000000, 2024-07-09T00:00:00.000000000, 2024-07-10T00:00:00.000000000, 2024-07-11T00:00:00.000000000, 2024-07-12T00:00:00.000000000, 2024-07-13T00:00:00.000000000, 2024-07-14T00:00:00.000000000, 2024-07-15T00:00:00.000000000, 2024-07-16T00:00:00.000000000, 2024-07-17T00:00:00.000000000, 2024-07-18T00:00:00.000000000, 2024-07-19T00:00:00.000000000, 2024-07-20T00:00:00.000000000, 2024-07-21T00:00:00.000000000, 2024-07-22T00:00:00.000000000, 2024-07-23T00:00:00.000000000, 2024-07-24T00:00:00.000000000, 2024-07-25T00:00:00.000000000, 2024-07-26T00:00:00.000000000, 2024-07-27T00:00:00.000000000, 2024-07-28T00:00:00.000000000, 2024-07-29T00:00:00.000000000, 2024-07-30T00:00:00.000000000, 2024-07-31T00:00:00.000000000, 2024-08-01T00:00:00.000000000, 2024-08-02T00:00:00.000000000, 2024-08-03T00:00:00.000000000, 2024-08-04T00:00:00.000000000, 2024-08-05T00:00:00.000000000, 2024-08-06T00:00:00.000000000, 2024-08-07T00:00:00.000000000, 2024-08-08T00:00:00.000000000, 2024-08-09T00:00:00.000000000, 2024-08-10T00:00:00.000000000, 2024-08-11T00:00:00.000000000, 2024-08-12T00:00:00.000000000, 2024-08-13T00:00:00.000000000, 2024-08-14T00:00:00.000000000, 2024-08-15T00:00:00.000000000, 2024-08-16T00:00:00.000000000, 2024-08-17T00:00:00.000000000, 2024-08-18T00:00:00.000000000, 2024-08-19T00:00:00.000000000, 2024-08-20T00:00:00.000000000, 2024-08-21T00:00:00.000000000, 2024-08-22T00:00:00.000000000, 2024-08-23T00:00:00.000000000, 2024-08-24T00:00:00.000000000, 2024-08-25T00:00:00.000000000, 2024-08-26T00:00:00.000000000, 2024-08-27T00:00:00.000000000, 2024-08-28T00:00:00.000000000, 2024-08-29T00:00:00.000000000, 2024-08-30T00:00:00.000000000, 2024-08-31T00:00:00.000000000, 2024-09-01T00:00:00.000000000, 2024-09-02T00:00:00.000000000, 2024-09-03T00:00:00.000000000, 2024-09-04T00:00:00.000000000, 2024-09-05T00:00:00.000000000, 2024-09-06T00:00:00.000000000, 2024-09-07T00:00:00.000000000, 2024-09-08T00:00:00.000000000, 2024-09-09T00:00:00.000000000, 2024-09-10T00:00:00.000000000, 2024-09-11T00:00:00.000000000, 2024-09-12T00:00:00.000000000, 2024-09-13T00:00:00.000000000, 2024-09-14T00:00:00.000000000, 2024-09-15T00:00:00.000000000, 2024-09-16T00:00:00.000000000, 2024-09-17T00:00:00.000000000, 2024-09-18T00:00:00.000000000, 2024-09-19T00:00:00.000000000, 2024-09-20T00:00:00.000000000, 2024-09-21T00:00:00.000000000, 2024-09-22T00:00:00.000000000, 2024-09-23T00:00:00.000000000, 2024-09-24T00:00:00.000000000, 2024-09-25T00:00:00.000000000, 2024-09-26T00:00:00.000000000, 2024-09-27T00:00:00.000000000, 2024-09-28T00:00:00.000000000, 2024-09-29T00:00:00.000000000, 2024-09-30T00:00:00.000000000, 2024-10-01T00:00:00.000000000, 2024-10-02T00:00:00.000000000, 2024-10-03T00:00:00.000000000, 2024-10-04T00:00:00.000000000, 2024-10-05T00:00:00.000000000, 2024-10-06T00:00:00.000000000, 2024-10-07T00:00:00.000000000, 2024-10-08T00:00:00.000000000, ...]
[left]:  [17506.65600358527, 17315.790024668517, 17456.229007506558, 16092.302817067844, 17808.788631868276, 17681.82831802354, 16818.22986905081, 17342.978241428238, 17495.718776753583, 17277.60721146263, 17039.2660287273, 17494.89868287859, 17490.22876161316, 16659.565422980435, 17647.38581889771, 17182.94196285788, 16877.760415297576, 16989.641384385635, 17321.413055316687, 17154.193838274216, 16781.701679834085, 17471.158951624024, 16797.106821636437, 16557.066767838878, 16395.69842860746, 17058.173358844535, 17132.714562221987, 17162.079605050512, 17488.687635336388, 17568.67001605713, 17894.455815904614, 35381.24910075198, 36246.882961263436, 34945.71367369539, 34210.0164959909, 36139.753713130216, 35898.454867370994, 34789.653269271694, 36106.548207165775, 34388.21203184038, 33719.01992571702, 33441.0125505524, 36118.29964272705, 36259.900701901075, 35818.5551827569, 36104.59110380417, 35998.70721699014, 35358.30243474613, 34667.8928909864, 36152.61332407989, 36375.103782830665, 18937.820111861944, 20020.003771090254, 19142.528950688225, 19145.16540046096, 18137.31016712446, 19049.072990226796, 19018.86878229869, 19062.749645057003, 19148.851884257423, 19307.083123788212, 17828.892744115896, 28315.142183710177, 30258.478638551165, 31668.706497303087, 32328.414737989086, 30600.472103337048, 31934.338977243515, 29111.029537690294, 28719.48731962657, 31430.41902323999, 30514.398103542015, 30813.543540337374, 30756.548890513248, 29805.468144451985, 30152.59249783333, 30636.982178643575, 28675.751788187044, 31377.083629828267, 32280.763722496125, 32081.03822379393, 36721.88743404573, 37244.96028665831, 37200.97456636307, 39145.26908439464, 37110.98604773029, 38131.83213811388, 37768.47102545391, 37606.84046146604, 36291.9452731108, 34836.63028396908, 37110.01976783181, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]
[right]: [4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 4839.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 9677.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 8333.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]
At positional index 0, first diff: 17506.65600358527 != 4839.0
❌ Assertion FAILED for: Instrument_Amazon
Series are different

Series values are different (56.66667 %)
[index]: [2024-07-01T00:00:00.000000000, 2024-07-02T00:00:00.000000000, 2024-07-03T00:00:00.000000000, 2024-07-04T00:00:00.000000000, 2024-07-05T00:00:00.000000000, 2024-07-06T00:00:00.000000000, 2024-07-07T00:00:00.000000000, 2024-07-08T00:00:00.000000000, 2024-07-09T00:00:00.000000000, 2024-07-10T00:00:00.000000000, 2024-07-11T00:00:00.000000000, 2024-07-12T00:00:00.000000000, 2024-07-13T00:00:00.000000000, 2024-07-14T00:00:00.000000000, 2024-07-15T00:00:00.000000000, 2024-07-16T00:00:00.000000000, 2024-07-17T00:00:00.000000000, 2024-07-18T00:00:00.000000000, 2024-07-19T00:00:00.000000000, 2024-07-20T00:00:00.000000000, 2024-07-21T00:00:00.000000000, 2024-07-22T00:00:00.000000000, 2024-07-23T00:00:00.000000000, 2024-07-24T00:00:00.000000000, 2024-07-25T00:00:00.000000000, 2024-07-26T00:00:00.000000000, 2024-07-27T00:00:00.000000000, 2024-07-28T00:00:00.000000000, 2024-07-29T00:00:00.000000000, 2024-07-30T00:00:00.000000000, 2024-07-31T00:00:00.000000000, 2024-08-01T00:00:00.000000000, 2024-08-02T00:00:00.000000000, 2024-08-03T00:00:00.000000000, 2024-08-04T00:00:00.000000000, 2024-08-05T00:00:00.000000000, 2024-08-06T00:00:00.000000000, 2024-08-07T00:00:00.000000000, 2024-08-08T00:00:00.000000000, 2024-08-09T00:00:00.000000000, 2024-08-10T00:00:00.000000000, 2024-08-11T00:00:00.000000000, 2024-08-12T00:00:00.000000000, 2024-08-13T00:00:00.000000000, 2024-08-14T00:00:00.000000000, 2024-08-15T00:00:00.000000000, 2024-08-16T00:00:00.000000000, 2024-08-17T00:00:00.000000000, 2024-08-18T00:00:00.000000000, 2024-08-19T00:00:00.000000000, 2024-08-20T00:00:00.000000000, 2024-08-21T00:00:00.000000000, 2024-08-22T00:00:00.000000000, 2024-08-23T00:00:00.000000000, 2024-08-24T00:00:00.000000000, 2024-08-25T00:00:00.000000000, 2024-08-26T00:00:00.000000000, 2024-08-27T00:00:00.000000000, 2024-08-28T00:00:00.000000000, 2024-08-29T00:00:00.000000000, 2024-08-30T00:00:00.000000000, 2024-08-31T00:00:00.000000000, 2024-09-01T00:00:00.000000000, 2024-09-02T00:00:00.000000000, 2024-09-03T00:00:00.000000000, 2024-09-04T00:00:00.000000000, 2024-09-05T00:00:00.000000000, 2024-09-06T00:00:00.000000000, 2024-09-07T00:00:00.000000000, 2024-09-08T00:00:00.000000000, 2024-09-09T00:00:00.000000000, 2024-09-10T00:00:00.000000000, 2024-09-11T00:00:00.000000000, 2024-09-12T00:00:00.000000000, 2024-09-13T00:00:00.000000000, 2024-09-14T00:00:00.000000000, 2024-09-15T00:00:00.000000000, 2024-09-16T00:00:00.000000000, 2024-09-17T00:00:00.000000000, 2024-09-18T00:00:00.000000000, 2024-09-19T00:00:00.000000000, 2024-09-20T00:00:00.000000000, 2024-09-21T00:00:00.000000000, 2024-09-22T00:00:00.000000000, 2024-09-23T00:00:00.000000000, 2024-09-24T00:00:00.000000000, 2024-09-25T00:00:00.000000000, 2024-09-26T00:00:00.000000000, 2024-09-27T00:00:00.000000000, 2024-09-28T00:00:00.000000000, 2024-09-29T00:00:00.000000000, 2024-09-30T00:00:00.000000000, 2024-10-01T00:00:00.000000000, 2024-10-02T00:00:00.000000000, 2024-10-03T00:00:00.000000000, 2024-10-04T00:00:00.000000000, 2024-10-05T00:00:00.000000000, 2024-10-06T00:00:00.000000000, 2024-10-07T00:00:00.000000000, 2024-10-08T00:00:00.000000000, ...]
[left]:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 85122.70880010264, 93092.65334238451, 131562.20459218143, 133731.02393946578, 125503.0985385795, 104963.06743887812, 112810.03471811085, 122305.64600863813, 79741.96321152688, 27363.6119540956, 35436.04660478251, 36523.07974778616, 35480.562933539775, 38321.38539725413, 31145.86938294426, 35984.122115305145, 41196.603520364, 45835.97997823461, 45821.85101710035, 43543.928340025224, 42660.01874211602, 42381.912545731655, 42822.35591622287, 203983.9873614282, 206086.5047024494, 187960.29139600883, 186986.05814905468, 200573.74647315955, 209898.83121460376, 218022.15930249653, 181239.03520097537, 173354.94405799452, 155762.87272837156, 177886.59955583053, 193990.8199663274, 188303.6443580342, 189642.2259120869, 186949.69651807495, 277911.15254497173, 368715.83368859655, 523753.6095784724, 450927.75206334976, 490254.5793568831, 513940.1727678302, 508784.1347078206, 667969.8886052119, 892888.7073190025, 952236.487410667, 986904.9843221867, 837484.3641807103, 890492.5587756993, 839216.5556137982, 778596.6765575552, 845180.5400323053, 828401.1656073938, 638282.9626569743, 696473.1341015338, 706545.3880627246, 734828.0259088255, 651136.9779958951, 580341.1451155525, 560178.1219300237, 761366.1976867593, 446836.40782705654, ...]
[right]: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 22946.18128, 25894.41175, 35260.29258, 37632.52121, 36018.05412, 30373.70959, 30224.64282, 32640.788129999997, 21543.66567999999, 7334.18285, 9525.74827, 9995.780859999999, 9903.844130000001, 10257.51702, 8285.84792, 9500.59772, 10288.86008, 11972.289580000002, 11966.95094, 12003.96529, 11197.4002, 11142.06976, 11231.94626, 53262.72003, 53370.69908, 52712.27274, 55029.03049, 55236.78336, 55230.76734, 56197.57938, 49354.3, 45235.53, 44586.95, 51614.04929, 51431.87883, 51422.75011, 51285.52211, 50651.060580000005, 77698.28083, 101898.66898999998, 142456.55146999998, 131036.87693000001, 130199.84451000001, 132669.21119, 132155.89112000001, 151576.98775000003, 199770.42641000004, 213300.50468, 210086.15924, 188050.97761999996, 194600.5234, 185159.50918999995, 172523.03108000002, 194062.05391000005, 198155.41447999998, 143325.49433000005, 151876.49198, 158611.85011, 158392.37071000005, 141187.49601, 129635.31014000002, 129110.55703000001, 173865.11873000002, 99580.66017000002, ...]
At positional index 36, first diff: 85122.70880010264 != 22946.18128
❌ Assertion FAILED for: Instrument_Best_Buy
Series are different

Series values are different (50.55556 %)
[index]: [2024-07-01T00:00:00.000000000, 2024-07-02T00:00:00.000000000, 2024-07-03T00:00:00.000000000, 2024-07-04T00:00:00.000000000, 2024-07-05T00:00:00.000000000, 2024-07-06T00:00:00.000000000, 2024-07-07T00:00:00.000000000, 2024-07-08T00:00:00.000000000, 2024-07-09T00:00:00.000000000, 2024-07-10T00:00:00.000000000, 2024-07-11T00:00:00.000000000, 2024-07-12T00:00:00.000000000, 2024-07-13T00:00:00.000000000, 2024-07-14T00:00:00.000000000, 2024-07-15T00:00:00.000000000, 2024-07-16T00:00:00.000000000, 2024-07-17T00:00:00.000000000, 2024-07-18T00:00:00.000000000, 2024-07-19T00:00:00.000000000, 2024-07-20T00:00:00.000000000, 2024-07-21T00:00:00.000000000, 2024-07-22T00:00:00.000000000, 2024-07-23T00:00:00.000000000, 2024-07-24T00:00:00.000000000, 2024-07-25T00:00:00.000000000, 2024-07-26T00:00:00.000000000, 2024-07-27T00:00:00.000000000, 2024-07-28T00:00:00.000000000, 2024-07-29T00:00:00.000000000, 2024-07-30T00:00:00.000000000, 2024-07-31T00:00:00.000000000, 2024-08-01T00:00:00.000000000, 2024-08-02T00:00:00.000000000, 2024-08-03T00:00:00.000000000, 2024-08-04T00:00:00.000000000, 2024-08-05T00:00:00.000000000, 2024-08-06T00:00:00.000000000, 2024-08-07T00:00:00.000000000, 2024-08-08T00:00:00.000000000, 2024-08-09T00:00:00.000000000, 2024-08-10T00:00:00.000000000, 2024-08-11T00:00:00.000000000, 2024-08-12T00:00:00.000000000, 2024-08-13T00:00:00.000000000, 2024-08-14T00:00:00.000000000, 2024-08-15T00:00:00.000000000, 2024-08-16T00:00:00.000000000, 2024-08-17T00:00:00.000000000, 2024-08-18T00:00:00.000000000, 2024-08-19T00:00:00.000000000, 2024-08-20T00:00:00.000000000, 2024-08-21T00:00:00.000000000, 2024-08-22T00:00:00.000000000, 2024-08-23T00:00:00.000000000, 2024-08-24T00:00:00.000000000, 2024-08-25T00:00:00.000000000, 2024-08-26T00:00:00.000000000, 2024-08-27T00:00:00.000000000, 2024-08-28T00:00:00.000000000, 2024-08-29T00:00:00.000000000, 2024-08-30T00:00:00.000000000, 2024-08-31T00:00:00.000000000, 2024-09-01T00:00:00.000000000, 2024-09-02T00:00:00.000000000, 2024-09-03T00:00:00.000000000, 2024-09-04T00:00:00.000000000, 2024-09-05T00:00:00.000000000, 2024-09-06T00:00:00.000000000, 2024-09-07T00:00:00.000000000, 2024-09-08T00:00:00.000000000, 2024-09-09T00:00:00.000000000, 2024-09-10T00:00:00.000000000, 2024-09-11T00:00:00.000000000, 2024-09-12T00:00:00.000000000, 2024-09-13T00:00:00.000000000, 2024-09-14T00:00:00.000000000, 2024-09-15T00:00:00.000000000, 2024-09-16T00:00:00.000000000, 2024-09-17T00:00:00.000000000, 2024-09-18T00:00:00.000000000, 2024-09-19T00:00:00.000000000, 2024-09-20T00:00:00.000000000, 2024-09-21T00:00:00.000000000, 2024-09-22T00:00:00.000000000, 2024-09-23T00:00:00.000000000, 2024-09-24T00:00:00.000000000, 2024-09-25T00:00:00.000000000, 2024-09-26T00:00:00.000000000, 2024-09-27T00:00:00.000000000, 2024-09-28T00:00:00.000000000, 2024-09-29T00:00:00.000000000, 2024-09-30T00:00:00.000000000, 2024-10-01T00:00:00.000000000, 2024-10-02T00:00:00.000000000, 2024-10-03T00:00:00.000000000, 2024-10-04T00:00:00.000000000, 2024-10-05T00:00:00.000000000, 2024-10-06T00:00:00.000000000, 2024-10-07T00:00:00.000000000, 2024-10-08T00:00:00.000000000, ...]
[left]:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]
[right]: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]
At positional index 184, first diff: 12535.073908059914 != 3397.8
❌ Assertion FAILED for: Instrument_Bing
Series are different

Series values are different (65.92593 %)
[index]: [2024-07-01T00:00:00.000000000, 2024-07-02T00:00:00.000000000, 2024-07-03T00:00:00.000000000, 2024-07-04T00:00:00.000000000, 2024-07-05T00:00:00.000000000, 2024-07-06T00:00:00.000000000, 2024-07-07T00:00:00.000000000, 2024-07-08T00:00:00.000000000, 2024-07-09T00:00:00.000000000, 2024-07-10T00:00:00.000000000, 2024-07-11T00:00:00.000000000, 2024-07-12T00:00:00.000000000, 2024-07-13T00:00:00.000000000, 2024-07-14T00:00:00.000000000, 2024-07-15T00:00:00.000000000, 2024-07-16T00:00:00.000000000, 2024-07-17T00:00:00.000000000, 2024-07-18T00:00:00.000000000, 2024-07-19T00:00:00.000000000, 2024-07-20T00:00:00.000000000, 2024-07-21T00:00:00.000000000, 2024-07-22T00:00:00.000000000, 2024-07-23T00:00:00.000000000, 2024-07-24T00:00:00.000000000, 2024-07-25T00:00:00.000000000, 2024-07-26T00:00:00.000000000, 2024-07-27T00:00:00.000000000, 2024-07-28T00:00:00.000000000, 2024-07-29T00:00:00.000000000, 2024-07-30T00:00:00.000000000, 2024-07-31T00:00:00.000000000, 2024-08-01T00:00:00.000000000, 2024-08-02T00:00:00.000000000, 2024-08-03T00:00:00.000000000, 2024-08-04T00:00:00.000000000, 2024-08-05T00:00:00.000000000, 2024-08-06T00:00:00.000000000, 2024-08-07T00:00:00.000000000, 2024-08-08T00:00:00.000000000, 2024-08-09T00:00:00.000000000, 2024-08-10T00:00:00.000000000, 2024-08-11T00:00:00.000000000, 2024-08-12T00:00:00.000000000, 2024-08-13T00:00:00.000000000, 2024-08-14T00:00:00.000000000, 2024-08-15T00:00:00.000000000, 2024-08-16T00:00:00.000000000, 2024-08-17T00:00:00.000000000, 2024-08-18T00:00:00.000000000, 2024-08-19T00:00:00.000000000, 2024-08-20T00:00:00.000000000, 2024-08-21T00:00:00.000000000, 2024-08-22T00:00:00.000000000, 2024-08-23T00:00:00.000000000, 2024-08-24T00:00:00.000000000, 2024-08-25T00:00:00.000000000, 2024-08-26T00:00:00.000000000, 2024-08-27T00:00:00.000000000, 2024-08-28T00:00:00.000000000, 2024-08-29T00:00:00.000000000, 2024-08-30T00:00:00.000000000, 2024-08-31T00:00:00.000000000, 2024-09-01T00:00:00.000000000, 2024-09-02T00:00:00.000000000, 2024-09-03T00:00:00.000000000, 2024-09-04T00:00:00.000000000, 2024-09-05T00:00:00.000000000, 2024-09-06T00:00:00.000000000, 2024-09-07T00:00:00.000000000, 2024-09-08T00:00:00.000000000, 2024-09-09T00:00:00.000000000, 2024-09-10T00:00:00.000000000, 2024-09-11T00:00:00.000000000, 2024-09-12T00:00:00.000000000, 2024-09-13T00:00:00.000000000, 2024-09-14T00:00:00.000000000, 2024-09-15T00:00:00.000000000, 2024-09-16T00:00:00.000000000, 2024-09-17T00:00:00.000000000, 2024-09-18T00:00:00.000000000, 2024-09-19T00:00:00.000000000, 2024-09-20T00:00:00.000000000, 2024-09-21T00:00:00.000000000, 2024-09-22T00:00:00.000000000, 2024-09-23T00:00:00.000000000, 2024-09-24T00:00:00.000000000, 2024-09-25T00:00:00.000000000, 2024-09-26T00:00:00.000000000, 2024-09-27T00:00:00.000000000, 2024-09-28T00:00:00.000000000, 2024-09-29T00:00:00.000000000, 2024-09-30T00:00:00.000000000, 2024-10-01T00:00:00.000000000, 2024-10-02T00:00:00.000000000, 2024-10-03T00:00:00.000000000, 2024-10-04T00:00:00.000000000, 2024-10-05T00:00:00.000000000, 2024-10-06T00:00:00.000000000, 2024-10-07T00:00:00.000000000, 2024-10-08T00:00:00.000000000, ...]
[left]:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]

In [7]:
# --- Load in cleaned master dataset

master = pd.read_parquet(os.getenv("MASTER_DATA_PATH"))

# Attaching Other Controls

#### This breaks the beautiful modular approach, but there's a lot that needs to get fixed in here.

#### Biggest issue: _The FRED API call for the specific indices is currently being built_

- `Media Measurement/modules/macro_tools_f.py.old` is the deprecated vibe-code version
- `Media Measurement/modules/macro_tools.ipynb` is the work-in-progress new version that should eventually be modularized to a `.py` import

### The following blocks attach controls which include:

- Macroeconomic Indices:
  - **30-day lagged PCE:** PCE or personal consumption expenditure is an index of US consumer spending often used to model inflation. It is used in place of CPI to help address measurement error.
  - **7-day lagged WEI:** WEI is the weekly economic index and is a high frequency measure of economic activity, again designed to achieve the same result as CPI but more reflective of average consumer experience.
- Reverse Causality Controls:
  - **Lagged GAs:** In order to address the specific perforance issue of business performance driving investment, we use lagged outcomes to control for reverse causality. A 7 day lag is the default specification.

In [8]:
# --- Economic Controls

from modules.macro_tools import attach_macro_controls
master = attach_macro_controls(
    master,
    date_col="Date",
    lag_pce_days=30,   # conservative for PCE
    lag_wei_days=7,    # weekly cadence
    standardize=True
)

ModuleNotFoundError: No module named 'modules.macro_tools'

In [ ]:
# --- Reverse Causality Controls

from modules.reverse_causality_controls import create_lagged_features
master = create_lagged_features(
    master,
    target_col = 'Total_GAs',
    lag_days = [7],
    date_col = 'Date',
    group_col = None,
    dropna = True
)

In [ ]:
# --- Pickle the Final dataset to parquet for exporting, databricks, and analysis
master.to_parquet('./data/master.parquet')